version: '3.4'

networks:
  default:
    name: apps
    external: true

services:

  uf1:
    image: local/universalforwarder:9.1.1
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 9.1.1
        TOOL: universalforwarder
    container_name: uf1
    hostname: uf1
    environment:
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_universal_forwarder
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_INDEXER_URL: sbs
      SPLUNK_PASSWORD: password
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
    - ${HOME}/projects:/projects
