version: '3.4'

networks:
  default:
    name: apps
    external: true

services:

  sh1:
    image: local/splunk:9.1.1
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 9.1.1
        TOOL: splunk
    container_name: sh1
    hostname: sh1
    ports:
    - "8200:8000"
    - "8289:8089"
    environment:
      LANG: en_US.utf8
      SPLUNK_PASSWORD: password
      SPLUNK_DISABLE_POPUPS: "true"
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ROLE: splunk_search_head
      SPLUNK_CLUSTER_MASTER_URL: cm1
      SPLUNK_IDXC_PASS4SYMMKEY: cm_and_indexer_comms
      SPLUNK_IDXC_DISCOVERYPASS4SYMMKEY: cm_and_forwarder_comms
    volumes:
      - D:\docker_storage\projects:/projects
      - D:\docker_storage\projects\apps:/opt/splunk/etc/apps
