version: '3.4'

networks:
  default:
    name: apps

services:

  sbs:
    image: local/splunk:9.1.1
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 9.1.1
        TOOL: splunk
    container_name: sbs
    hostname: sbs
    ports:
    - "8000:8000"
    - "8089:8089"
    - "8088:8088"
    environment:
      SPLUNK_DISABLE_POPUPS: "true"
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_standalone
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
      SPLUNK_HEC_TOKEN: password
    volumes:
    - D:\docker_storage\projects:/projects
  
  sbf:
    image: local/universalforwarder:9.1.1
    build:
      context: ../.images/splunk
      network: host
      args:
        VERSION: 9.1.1
        TOOL: universalforwarder
    container_name: sbf
    hostname: sbf
    environment:
      LANG: en_US.utf8
      SPLUNK_ROLE: splunk_universal_forwarder
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_INDEXER_URL: sbs
      SPLUNK_PASSWORD: password
    volumes:
    - D:\docker_storage\projects:/projects
